<?php defined('PHPFOX') or exit('NO DICE!'); ?>
<?php $aContent = array (
  'younet_jobposting{3}' => 
  array (
    'key' => 'younet_jobposting',
    'name' => 'Job Posting',
    'current_v' => '3.01p2',
    'latest_v' => '3.01p2',
    'demo_url' => 'http://phpfox3.demo.younetco.com/jobposting/',
    'image_url' => 'http://phpfox.younetco.com/files/2013/06/FPosting_logo_1.jpg',
    'purchase' => 'http://phpfox.younetco.com/job-posting.html',
    'download' => '',
    'price' => '70.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Job Posting allows you to run and manage a job board in your social network. This module creates a professional environment for your members to do business. In other words, Job Posting not only enables your members to promote their businesses but also offers job opportunities for your community. With Job Posting, your site will earn reputation by providing quality jobs and attract more users to join. 
The module also allow you to charge your members and earn nice addition income by providing some functions: feature or sponsor a job posts, add packages with different cost and duration.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_mfox{3}' => 
  array (
    'key' => 'younet_mfox',
    'name' => 'phpFox Mobile',
    'current_v' => '3.01',
    'latest_v' => '3.01',
    'demo_url' => 'https://play.google.com/store/apps/details?id=com.younetco.mobifox#?t=W251bGwsMSwyLDIxMiwiY29tLnlvdW5ldGNvLm1vYmlmb3giXQ..',
    'image_url' => 'http://phpfox.younetco.com/files/2013/06/mobifox_icon.png',
    'purchase' => 'http://phpfox.younetco.com/phpfox-androi-application.html',
    'download' => '',
    'price' => '200.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'This application is specially designed for Android Device with the purpose of increasing interaction between members and your community. Your members are now able to access your community from everywhere to share instant updates and social activities. Android application also provides easy way to browse photos, send message, and participate in any event and more valuable features that your members will surely want to experience and enjoy.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_birthdayreminder{3}' => 
  array (
    'key' => 'younet_birthdayreminder',
    'name' => 'YouNet Birthday Reminder',
    'current_v' => '3.01',
    'latest_v' => '3.01',
    'demo_url' => 'http://phpfox3.demo.younetco.com',
    'image_url' => 'http://phpfox.younetco.com/files/2013/05/birthdayreminder_logo.jpg',
    'purchase' => 'http://phpfox.younetco.com/birthday-reminder.html',
    'download' => '',
    'price' => '0.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'If you would like to remind your member to stay connect with your site, Birthday Reminder is the ideal tool. Birthday Reminder will send happy birthday emails to members with option to create events. In order words, Birthday Reminder will remind your members to visit the site in order to see what is new and stay longer with your site.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_contest{3}' => 
  array (
    'key' => 'younet_contest',
    'name' => 'Contest',
    'current_v' => '3.01p3',
    'latest_v' => '3.01p3',
    'demo_url' => ' http://phpfox3.demo.younetco.com/contest/',
    'image_url' => 'http://phpfox.younetco.com/files/2013/04/contest_fox_logo.jpg',
    'purchase' => 'http://phpfox.younetco.com/v3-contest.html',
    'download' => '',
    'price' => '55.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Contest is a module which allows your members to compete with each others in Blog, Photo and Video contests. Each time creating a contest, contest owner can completely himself define the rules as well as the award to attract other members to take part in. Promote Contest is also a worth feature. It will generate a code to embed the contest to other external websites. That is to say, more people will know about your site via the contest and as a result, the traffic will be increased. However, this has not been the best feature yet. By installing Contest, you are completely able to make a little profit from its operation. Beside Publishing Fee is a compulsory one, Feature; Preminum and Ending Soon are other kinds of fee that members have to pay to you if they would like their contests to be more attractive to other members. Increasing traffic and making profit, what can be more interesting?',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_coupon{3}' => 
  array (
    'key' => 'younet_coupon',
    'name' => 'Coupon',
    'current_v' => '3.02p2',
    'latest_v' => '3.02p2',
    'demo_url' => 'http://phpfox3.demo.younetco.com/coupon/',
    'image_url' => 'http://phpfox.younetco.com/files/2013/03/fox_coupon_logo.jpg',
    'purchase' => 'http://phpfox.younetco.com/coupon.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Coupon is an effective assistance for your members who are doing trading. Whenever they would like to run a promote, simply go to your site and create a coupon. This coupon will give out code for other people to get discount from them.
Coupon not only make your site traffic increased but also give you profit. Whenever your members would like to publish or make a coupon featured, a small fee will go straight to your account.
What could be more interesting?',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_osticket{3}' => 
  array (
    'key' => 'younet_osticket',
    'name' => 'osTicket Integration',
    'current_v' => '3.02',
    'latest_v' => '3.02',
    'demo_url' => 'http://phpfox3.demo.younetco.com/osticket/',
    'image_url' => 'http://phpfox.younetco.com/files/2013/02/osticket_fox_logo.png',
    'purchase' => 'http://phpfox.younetco.com/osticket-integration.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'If you are a webmaster, OsTicket is a perfect platform which help you communicate and listen to your members’ feedback. So, just imagine how wonderful it will be if your OsTicket and phpFox site can be integrated with each other. Catching this tendency, we would like to introduce to you OsTicket Integration.

After installing this module, when a member would like to communicate with you, no longer will he have to navigate away to OsTicket to submit a ticket but doing it directly on your site.

In a word, this module will make your system more simple to members since all their actions happen on your site only.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_mailchimp{3}' => 
  array (
    'key' => 'younet_mailchimp',
    'name' => 'phpFox - MailChimp Integration',
    'current_v' => '3.01p1',
    'latest_v' => '3.01p1',
    'demo_url' => 'http://phpfox3.demo.younetco.com/mailchimp',
    'image_url' => 'http://phpfox.younetco.com/files/2013/02/phpfox_mailchimp_logo.png',
    'purchase' => 'http://phpfox.younetco.com/mailchimp-integration.html',
    'download' => '',
    'price' => '70.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Should you be the webmaster of a site then communicating with members via e-mail is always an important issue. The thing is, sending a large number of e-mails in a time takes your site a lot of resource as well as time to mange. Basing on this demand, we are now glad to bring to you: MailChimp Integration.

There is nothing more to say about MailChimp since this is a famous service which assists webmasters to send a large number of newsletters to site members. MailChimp Integration is just an improvement from YouNet which helps your phpFox site connect to MailChimp. Once finishing installing, you will be able to import all e-mail addresses of your members to MailChimp, separate them into group, define the e-mail template to be sent to specific group then MailChimp will take care of the rest.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_profilepopup{3}' => 
  array (
    'key' => 'younet_profilepopup',
    'name' => 'Profile Popup',
    'current_v' => '3.01p4',
    'latest_v' => '3.01p4',
    'demo_url' => 'http://phpfox3.demo.younetco.com/',
    'image_url' => 'http://phpfox.younetco.com/files/2013/01/phpfox_profile_popup.png',
    'purchase' => 'http://phpfox.younetco.com/profile-popup.html',
    'download' => '',
    'price' => '25.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'If you are tired of phpFox’s standard popup or you would like to make your site’s interface more attractive then Profile Popup is simply a right module that you can not miss.

After installing Profile Popup, whenever users hovering mouse over a member’s name; a page’s name or an event’s name, a small popup will be displayed to show out detailed information about this issue. You, as the admin of the site, will be completely and easily manage what to be poped-up in BackEnd.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'vbulletin{3}' => 
  array (
    'key' => 'vbulletin',
    'name' => 'YouNet vBB Integration',
    'current_v' => '3.01p4',
    'latest_v' => '3.01p4',
    'demo_url' => 'http://integration.demo.younetco.com/phpfox-vbb/phpfox/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/12/phpFox-vBB-logo.png',
    'purchase' => 'http://phpfox.younetco.com/younet-vbb-integration.html',
    'download' => '',
    'price' => '100.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'This module is an effective assistance in decreasing the administration effort and increasing the interaction between your phpFox site and your vBulletin forum. Just imagine you are simultaneously the admin of a phpFox site and a vBulletin forum, what can be more amazing than your users’ capability of accessing the two platforms with one registration? With YouNet vBB Integration being installed, all of the database between your site and your forum will be synchronized. Each time a user creates an account on forum or site, this account will be synced to the other. Moreover, information field of the account on the two platforms will be appropriately mapped according to your configurations in BackEnd.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'ynsnow{3}' => 
  array (
    'key' => 'ynsnow',
    'name' => 'Snow Falling Effect',
    'current_v' => '3.01',
    'latest_v' => '3.01',
    'demo_url' => 'http://phpfox3.demo.younetco.com/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/12/snowfall.png',
    'purchase' => 'http://phpfox.younetco.com/v3-snow-fall.html',
    'download' => '',
    'price' => '0.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'It is totally convinced that you know nothing about Christmas if you have never once played under falling snow. However, it seems to be a starry-eyed with those who live in tropical countries. This year, with Snow Fall we will bring Christmas to your site.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_resume{3}' => 
  array (
    'key' => 'younet_resume',
    'name' => 'Resume',
    'current_v' => '3.03',
    'latest_v' => '3.03',
    'demo_url' => 'http://phpfox3.demo.younetco.com/resume/',
    'image_url' => 'http://phpfox.younetco.com/files/2013/01/phpfox_resume_logo.png',
    'purchase' => 'http://phpfox.younetco.com/v3-resume.html',
    'download' => '',
    'price' => '70.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Resume is a module which will turn your site into the contact point between employers and employees.

Your site with Resume installed will be an efficient assistance to members who are in need of recruiting. By registering the “View Resume” service, they will have the right to view the full version of other members’ resumes, study them then making a list of candidates they think the most suitable. Moreover, with a contact tool integrated, the employers will not have to use another email address or phone number to contact the candidates but do it directly via your site.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_fundraising{3}' => 
  array (
    'key' => 'younet_fundraising',
    'name' => 'Fund Raising',
    'current_v' => '3.01p5',
    'latest_v' => '3.01p5',
    'demo_url' => 'phpfox3.demo.younetco.com/fundraising/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/12/phpfox-fundraising-logo.png',
    'purchase' => 'http://phpfox.younetco.com/v3-fund-raising.html',
    'download' => '',
    'price' => '75.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'This is a module which will give your site members a hand in financial aspect. If your members are nursing big ideas but have to give up because of shortage of expense, with Fund Raising being installed, your site will be their savior.

By creating campaign via Fund Raising, your members can give out detailed information about the ideas they have or the projects they are working on as well as the expenses they are in need  then appeal other people to raise fund.

Being a module which has similar traits to Donation in purpose, Fund Raising has significant innovations in feature and interface. With Fund Raising, donors now will know exactly the reason of donating, whom they donate to, etc. Especially, campaigns are now not only known site wide but also extended to other website. Each campaign now has a source code to form an advertising block to embed to other external websites. This will bring your members’ campaigns to more people. The more people know, the more money they can raise, the more popular your site will be.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'advancedphoto{3}' => 
  array (
    'key' => 'advancedphoto',
    'name' => 'Advanced Photo',
    'current_v' => '3.01p7',
    'latest_v' => '3.01p7',
    'demo_url' => 'http://phpfox3.demo.younetco.com/advancedphoto/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/10/advphoto.png',
    'purchase' => 'http://phpfox.younetco.com/advanced-photo.html',
    'download' => '',
    'price' => '60.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Being developed from Fox Photo, Advanced Photo is inherited basic features and at the same time improved with new ones. With Advanced Photo, your members can tag friends to their photos or albums to notify or embed them to other external website by using Badge Code and so on.

Interface is a huge innovation. All featured photos and albums are displayed in slideshow, view a photo in popup window like Facebook, view photos of an album in slideshow mode with effect, My Photo is built in TimeLine structure, etc.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younetkaraoke{3}' => 
  array (
    'key' => 'younetkaraoke',
    'name' => 'YouNet Karaoke',
    'current_v' => '3.01p2',
    'latest_v' => '3.01p2',
    'demo_url' => 'http://phpfox3.demo.younetco.com/karaoke',
    'image_url' => 'http://phpfox.younetco.com/files/2012/10/kara.png',
    'purchase' => 'http://phpfox.younetco.com/v3-karaoke.html',
    'download' => '',
    'price' => '70.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Karaoke is a module which help entertainment your users. This module allows you to upload a lot of instrumental music and make them as karaoke style for your members to sing. Moreover, it also records their voice as a mini studio to share with other people. With Karaoke, no longer do your members have to waste money for studio or professional karaoke system but spending time on your site.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'pagecontacts{3}' => 
  array (
    'key' => 'pagecontacts',
    'name' => 'Page Contact Form',
    'current_v' => '3.01p2',
    'latest_v' => '3.01p2',
    'demo_url' => 'http://phpfox3.demo.younetco.com/pages/153/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/07/contactform_logo.png',
    'purchase' => 'http://phpfox.younetco.com/v3-page-contact-form.html',
    'download' => '',
    'price' => '15.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'If you need a tool to allow your members to communicate with the Page owner directly, our Page Contact Form is the best choice for you. By using this plugin, your Page owners can adjust the contact form based on their business and your member have an immediate, convenient way to ask the page owners their questions.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'FoxFeedsPro{3}' => 
  array (
    'key' => 'FoxFeedsPro',
    'name' => 'Fox Feeds Pro',
    'current_v' => '3.03p3',
    'latest_v' => '3.03p3',
    'demo_url' => 'http://phpfox3.demo.younetco.com/foxfeedspro/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/07/ultimatenews.png',
    'purchase' => 'http://phpfox.younetco.com/v3-fox-feeds-pro.html',
    'download' => '',
    'price' => '70.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'FoxFeeds Pro is inspired by one of our best-selling modules, News Feed, with significant improvement based on client’s need on content parsing.

With News Feed, your members must go to RSS provider website to read for the full content, which now is not necessary once the content could be read on your site with FoxFeeds Pro. FoxFeeds Pro comes with a new RSS reader along with a full content parsing component which allows reading the whole content of the RSS feeds. So, in order to read the article, members do not need to navigate away from your website any more. This will help visitors stay longer in your website.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'fanot{3}' => 
  array (
    'key' => 'fanot',
    'name' => 'Advanced Feed Notification',
    'current_v' => '3.02p1',
    'latest_v' => '3.02p1',
    'demo_url' => 'http://phpfox3.demo.younetco.com',
    'image_url' => 'http://phpfox.younetco.com/files/2012/06/advanced_notification_logo.png',
    'purchase' => 'http://phpfox.younetco.com/v3-advanced-feed-notification.html',
    'download' => '',
    'price' => '20.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Advanced Feed Notification allows members to receive all types of notification associated with their feeds under small box in the left bottom corner. Members therefore get updated notifications and click to view new notifications easily.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'foxfavorite{3}' => 
  array (
    'key' => 'foxfavorite',
    'name' => 'Fox Favorite',
    'current_v' => '3.02p2',
    'latest_v' => '3.02p2',
    'demo_url' => 'http://phpfox3.demo.younetco.com/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/06/fox_favorite.png',
    'purchase' => 'http://phpfox.younetco.com/v3-fox-favorite.html',
    'download' => '',
    'price' => '35.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Fox Favorite plugin is a great tool to allow your members to favor other members or any item of basic modules on phpFox. Your members can view the favorite members or items very easily on both Home Page or their Profile Page.

Furthermore, your members can receive notifications from their favorite members’ activities such as: add status, photo, link, poll, blog, music.  This plugin also includes many interesting blocks that show who follows them, top favorite members, top favorite page, etc.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'socialmediaimporter{3}' => 
  array (
    'key' => 'socialmediaimporter',
    'name' => 'Social Media Importer',
    'current_v' => '3.02p6',
    'latest_v' => '3.02p6',
    'demo_url' => 'http://phpfox3.demo.younetco.com/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/06/Social_Media_Importer.png',
    'purchase' => 'http://phpfox.younetco.com/v3-social-media-importer.html',
    'download' => '',
    'price' => '45.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Social Media Importer is a right tool for your members if you want to enrich your site. It imports Photo from other top social networks like Facebook, Instagram,Flickr and Picasa. Members will be able to get their photos from other social networks and set these photos to be either private or public through “Privacy Setting”

More importantly, with huge improvement in performance and usability, members are now able to import a huge amount of photos from other social network site mentioned above. Cronjob is also applied to allow importing process run in background, which will not affect your site performance',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'socialstream{3}' => 
  array (
    'key' => 'socialstream',
    'name' => 'Social Stream',
    'current_v' => '3.03',
    'latest_v' => '3.03',
    'demo_url' => 'http://phpfox3.demo.younetco.com/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/05/Social_Stream_Logo.png',
    'purchase' => 'http://phpfox.younetco.com/v3-social-stream.html',
    'download' => '',
    'price' => '45.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'How many of your members have Facebook and Twitter accounts, and how many publish feeds on their Walls every hour? If all the feeds could be fed to your phpFox community, it would be a great idea to keep your members staying longer on your site, and your site will become more lively. Social Stream plugin makes this dream come true.

With Social Stream, your members will be able to get all activities from their Facebook’s Walls, Twitter accounts, such as new feed, tweet, someone sharing photo, video, even they have been tagged by others and so on. With “Privacy Setting”, members are able to set feed’s privacy to them, to their friends or to public. The ability to filter out feeds from Facebook, Twitter or site is also a plus; it keeps members’ wall in order.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_favoritepages{3}' => 
  array (
    'key' => 'younet_favoritepages',
    'name' => 'Favorite Page',
    'current_v' => '3.01',
    'latest_v' => '3.01',
    'demo_url' => 'http://phpfox3demo.modules2buy.com/pages/97/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/04/logo_favourite-page.jpg',
    'purchase' => 'http://phpfox.younetco.com/v3-page-favorite.html',
    'download' => '',
    'price' => '10.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => '',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_social_integration{3}' => 
  array (
    'key' => 'younet_social_integration',
    'name' => 'Social Integration',
    'current_v' => '3.01',
    'latest_v' => '3.01',
    'demo_url' => 'http://phpfox3demo.modules2buy.com/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/04/social_integration.png',
    'purchase' => 'http://phpfox.younetco.com/v3-social-integration.html',
    'download' => '',
    'price' => '30.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Integrating with Facebook’s Pages and Twitter is a great way to get additional exposure for your Page that belongs to a social network empowered by phpFox, whether you re-publish your Page’s feeds directly on Facebook’s Page and Twitter.

To accomodate that, our Social Integration plugin is a nice tool to integrate your Page with Facebook’s Page and Twitter.',
    'platform' => 'phpfox',
    'mode' => 'development',
    'platform_version' => '3',
  ),
  'advanced_marketplace{3}' => 
  array (
    'key' => 'advanced_marketplace',
    'name' => 'Advanced Marketplace',
    'current_v' => '3.02p4',
    'latest_v' => '3.02p4',
    'demo_url' => 'http://phpfox3.demo.younetco.com/advancedmarketplace/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/03/advanced-marketplace.jpg',
    'purchase' => 'http://phpfox.younetco.com/v3-advanced-market-place.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Served as an improvement to phpFox Marketplace, Advanced Marketplace plugin is a great tool to drive business for online merchants. It is equipped with the best product listings that enable sellers to promote their items more efficiently. This plugin also enables sellers to offer a variety of products and provide buyers with the convenience of purchasing such products from any single seller. In addition, buyers can rate a product, write a product review, or even follow up with sellers for more updates on their marketplace activities.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_petition{3}' => 
  array (
    'key' => 'younet_petition',
    'name' => 'Petition',
    'current_v' => '3.01p6',
    'latest_v' => '3.01p6',
    'demo_url' => 'http://phpfox3.demo.younetco.com/petition/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/03/petition-producticon.jpg',
    'purchase' => 'http://phpfox.younetco.com/v3-petition.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Make your voice heard by thousands of people around the world with our Petition module. This module not only allows you to create petition targeting decision makers all over the world, but also allows you to connect with other concerned individuals in support of a single cause. By creating your own petition, you can create a single point of action for anyone who might be interested in joining your campaign and would like to make a difference for a healthier, safer, and more equitable community.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'fblikebutton{3}' => 
  array (
    'key' => 'fblikebutton',
    'name' => 'FoxLike like Facebook-Like',
    'current_v' => '3.02p1',
    'latest_v' => '3.02p1',
    'demo_url' => 'http://phpfox3demo.modules2buy.com/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/03/LikeBox.png',
    'purchase' => 'http://phpfox.younetco.com/v3-fox-like.html',
    'download' => '',
    'price' => '10.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'As the owner of a web site that presents things like movies, sports teams, celebrities, and restaurants, you would want to share and to promote your web site content with friends on many social networks. And to accommodate that, our FoxLike plugin (equivalent to Facebook Like ) is the essential tool to have.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'donation_pages{3}' => 
  array (
    'key' => 'donation_pages',
    'name' => 'donationpages',
    'current_v' => '3.03p8',
    'latest_v' => '3.03p8',
    'demo_url' => 'http://phpfox3.demo.younetco.com/pages/96/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/02/PageDonation.png',
    'purchase' => 'http://phpfox.younetco.com/v3-donation.html',
    'download' => '',
    'price' => '20.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Using our Donation plugin is wonderful way to spread out the love, the inspiration, the motivation and a positive life by encouraging your members to contribute to those who are in need. With Donation plugin, you can set up a simple donation process that allows the members to offer any amount of money by simply clicking on the “Donate” button. It’s about doing. It’s about action. It’s about creating a brighter, healthier and more sustainable community. And it’s about having fun, together by helping others.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'tourguides{3}' => 
  array (
    'key' => 'tourguides',
    'name' => 'User tour guides',
    'current_v' => '3.02p3',
    'latest_v' => '3.02p3',
    'demo_url' => 'http://phpfox3demo.modules2buy.com/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/02/sitetour.jpg',
    'purchase' => 'http://phpfox.younetco.com/v3-tour-guide.html',
    'download' => '',
    'price' => '25.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Tour Guide is an essential tool to help you to create fully illustrated introduction for users. You can add  tour guide to any page and the number of tour guides in the whole system is not restricted. Your site will be more user friendly and attractive with this module.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'fblike{3}' => 
  array (
    'key' => 'fblike',
    'name' => 'Facebook Like-box',
    'current_v' => '3.01',
    'latest_v' => '3.01',
    'demo_url' => 'http://phpfox3demo.modules2buy.com',
    'image_url' => 'http://phpfox.younetco.com/files/2012/01/facebook-like.png',
    'purchase' => 'http://phpfox.younetco.com/facebook-social-like.html',
    'download' => '',
    'price' => '10.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Facebook Social Like plugin allows you to gain Likes from phpFox members in a fast and easy way. This plugin displays on your phpFox site different contents from your Facebook fan page  such as recent posts, activities, and the number of Likes, so your phpFox members will be able to follow up with those without leaving your site. This plugin is the best way to let you attract members to your Facebook fan page and to increase your phpFox site traffic.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'userutilities{3}' => 
  array (
    'key' => 'userutilities',
    'name' => 'User Utilities',
    'current_v' => '3.01p2',
    'latest_v' => '3.01p2',
    'demo_url' => 'http://phpfox3.demo.modules2buy.com',
    'image_url' => 'http://phpfox.younetco.com/files/2012/01/Userutilities.png',
    'purchase' => 'http://phpfox.younetco.com/v3-user-utilities.html',
    'download' => '',
    'price' => '15.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'User Utilities would come in handy when users want to reactive their deactivated accounts on social netowrk sites powered by phpFox. User Utilities plugin allows users to easily close their accounts with one simple mouse click. And to reactive their accounts, they can always return to the website to proceed a simple reactivation process.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younetevent{3}' => 
  array (
    'key' => 'younetevent',
    'name' => 'Advanced Event',
    'current_v' => '3.03p6',
    'latest_v' => '3.03p6',
    'demo_url' => 'http://phpfox3.demo.younetco.com/fevent',
    'image_url' => 'http://phpfox.younetco.com/files/2012/01/event_logo.png',
    'purchase' => 'http://phpfox.younetco.com/advanced-event.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Advanced Event plugin includes many features that help users manage their online event registration and make their events more successful and profitable. Custom field for event categories is a great tool which helps admin add more fields to event creation or event edition such as: website, event type, etc. Users can browse for interested events by advanced search criteria: description, month, past events and proximity search (location + distance). Also, with provided blocks such as Featured Events, Calendar, Past Events, Advanced Event makes it easier for user to access any site event.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'suggestion_recommendation{3}' => 
  array (
    'key' => 'suggestion_recommendation',
    'name' => 'Suggestion & Recommendation',
    'current_v' => '3.03p1',
    'latest_v' => '3.03p1',
    'demo_url' => 'http://phpfox3.demo.modules2buy.com',
    'image_url' => 'http://phpfox.younetco.com/files/2012/01/frec_logo.jpg',
    'purchase' => ' http://phpfox.younetco.com/v3-recommendation-suggestion.html',
    'download' => '',
    'price' => '60.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Running Recommendation & Suggestion plugin on phpFox network is a powerful way to increase user engagement in site’s activities, boost user’s friend count, and build a better user-base site and connection. With Suggestion & Recommendation, users not only receive friend suggestions from the system or from their friends but also receive various content suggestions such as join-a-Page suggestion, join-an-event suggestion, view-a-blog suggestion, watch-a-video suggestion, etc. These suggestions are shown to users through user-friendly widgets and popups. In addition, users may reject suggestions that they are not interested in, and such suggestions will not be shown to them again.

',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_videochannel{3}' => 
  array (
    'key' => 'younet_videochannel',
    'name' => 'Video Channel',
    'current_v' => '3.02p10',
    'latest_v' => '3.02p10',
    'demo_url' => 'http://phpfox3.demo.younetco.com/videochannel',
    'image_url' => 'http://phpfox.younetco.com/files/2011/05/videochanel.jpg',
    'purchase' => 'http://phpfox.younetco.com/v3-video-channel.html',
    'download' => '',
    'price' => '45.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Video Channel brings users the ability to collect videos from YouTube channels and gather those videos into their own channels on phpFox sites. This module separates and differs from phpFox Video module. With Video Channel, users can enjoy many YouTube videos, add them to their favorite list, comment on them and even rate those videos right on their phpFox sites.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'socialpublishers{3}' => 
  array (
    'key' => 'socialpublishers',
    'name' => 'Social Publishers',
    'current_v' => '3.04p1',
    'latest_v' => '3.04p1',
    'demo_url' => 'http://phpfox3.demo.modules2buy.com',
    'image_url' => 'http://phpfox.younetco.com/files/2012/01/logo_social_publisher_phpfox.png',
    'purchase' => 'http://phpfox.younetco.com/social-publisher.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Social Publisher is a safer, faster, and easier way to publish users’ activities and update users’ statuses on phpFox site  onto Wall of Facebook/Twitter/LinkedIn.  With Social Publisher, your website will be promoted as a friendly and professional network as well as a well-known social network.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'opensocialconnect{3}' => 
  array (
    'key' => 'opensocialconnect',
    'name' => 'Social Connect',
    'current_v' => '3.03p1',
    'latest_v' => '3.03p1',
    'demo_url' => 'http://phpfox3.demo.modules2buy.com',
    'image_url' => 'http://phpfox.younetco.com/files/2011/12/socialconnect.jpg',
    'purchase' => 'http://phpfox.younetco.com/v3-social-connect.html',
    'download' => '',
    'price' => '45.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Social Connect is a safe, faster, and easier way to log in by using existing accounts in Facebook, Twitter, Google, Yahoo, MySpace, LinkedIn, Windows Live, Hyves, and so on (up to 40 providers). With Social Connect, saving time to sign up and securing password will make your website more friendly, professional, and interactive. Social Connect not only helps you to reduce customer care and password recovery cost but also to achieve greater customer satisfaction by eliminating frustrations associated with forgotten user identities (usernames and passwords).',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'advancedshare{3}' => 
  array (
    'key' => 'advancedshare',
    'name' => 'Advanced Sharing',
    'current_v' => '3.02p9',
    'latest_v' => '3.02p9',
    'demo_url' => 'http://phpfox3.demo.modules2buy.com',
    'image_url' => 'http://phpfox.younetco.com/files/2011/12/Advanced_Sharing.png',
    'purchase' => 'http://phpfox.younetco.com/v3-advanced-sharing.html',
    'download' => '',
    'price' => '30.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Advanced Sharing is one of the best ways for users to share any particular content on phpFox site with other members by posting it on their own walls, their friends’ walls, or on their Pages’ wall. In addition, Advanced Sharing allows users to further define who can and cannot view certain information shared on their own walls.',
    'platform' => 'phpfox',
    'mode' => 'development',
    'platform_version' => '3',
  ),
  'younetwall{3}' => 
  array (
    'key' => 'younetwall',
    'name' => 'Advanced Wall',
    'current_v' => '3.03p6',
    'latest_v' => '3.03p6',
    'demo_url' => 'http://phpfox3.demo.younetco.com/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/10/advancedwall.png',
    'purchase' => 'http://phpfox.younetco.com/v3-advanced-wall.html',
    'download' => '',
    'price' => '40.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Like Facebook Wall, Advanced Wall plugin empowers users to engage in phpFox site activities by posting messages with emoticons, tagging friends within a message, and filtering feeds to be shown on their walls. In addition, users are able to have a quick view of content from a link.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'musicstore{3}' => 
  array (
    'key' => 'musicstore',
    'name' => 'Music Store',
    'current_v' => '3.01p7',
    'latest_v' => '3.01p7',
    'demo_url' => 'http://phpfox3.demo.younetco.com/musicstore/musicstore',
    'image_url' => 'http://phpfox.younetco.com/files/2012/06/advanced_music.jpg',
    'purchase' => 'http://phpfox.younetco.com/music-store-v3.html',
    'download' => '',
    'price' => '120.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Music Store is an enhancement to our Music Sharing plugin that enables users to engage in music selling / buying transactions on phpFox sites. Users can upload music to share or to sell. Admin can define commission rate for transactions. There are many back end features supporting Admin to manage music selling business on phpFox sites.',
    'platform' => 'phpfox',
    'mode' => 'development',
    'platform_version' => '3',
  ),
  'YouNetNews{3}' => 
  array (
    'key' => 'YouNetNews',
    'name' => 'News Feed',
    'current_v' => '3.02p4',
    'latest_v' => '3.02p4',
    'demo_url' => 'http://phpfox3.demo.younetco.com/newsfeed',
    'image_url' => 'http://phpfox.younetco.com/files/2012/06/newsfeed.png',
    'purchase' => 'http://phpfox.younetco.com/news-feed-v3.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'News Feed plugin, a RSS Feed Reader, empowers phpFox sites to auto stream popular and latest news from other sites to phpFox sites. This plugin allows users to avoid manually inspecting all of the websites they are interested in, and instead subscribe to websites such that all news content is pushed onto their phpFox sites when it becomes available. Also, latest news belongs to added RSS feeds can be automatically  updated and displayed at a specific time by setting the schedule.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'userconnect{3}' => 
  array (
    'key' => 'userconnect',
    'name' => 'User Connection',
    'current_v' => '3.02p5',
    'latest_v' => '3.02p5',
    'demo_url' => 'http://phpfox3demo.modules2buy.com/userconnect/view/',
    'image_url' => 'http://phpfox.younetco.com/files/2011/09/UserConnection.jpg',
    'purchase' => 'http://phpfox.younetco.com/user-connection-v3.html',
    'download' => '',
    'price' => '25.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'User Connections plugin allows users to extend their friend networks and establish their relationship map by exploring friends of their friends. Many included features are effective tools to connect friends on the relationship map. “People You May Know” feature helps users find and connect with other members via their current friends. “Shortest Connection Path” allows users to view the shortest path to connect with other users. In addition, users can find out about people whom they are likely to add friends via suggested relationships from: 2nd level contacts, 3rd level contacts, etc.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'profilecompleteness{3}' => 
  array (
    'key' => 'profilecompleteness',
    'name' => 'User Profile Completeness Like LinkedIn',
    'current_v' => '3.02p2',
    'latest_v' => '3.02p2',
    'demo_url' => 'http://phpfox3demo.modules2buy.com',
    'image_url' => 'http://phpfox.younetco.com/files/2011/12/ProfileCompleteness.png',
    'purchase' => 'http://phpfox.younetco.com/user-profile-completeness-like-likedin-v3.html',
    'download' => '',
    'price' => '15.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'User Profile Completeness is the block that  shows own profile completeness status. It allows administrators to select profile fields as mandatory for a user to achieve 100% profile completeness status.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'musicsharing{3}' => 
  array (
    'key' => 'musicsharing',
    'name' => 'Music Sharing',
    'current_v' => '3.03p3',
    'latest_v' => '3.03p3',
    'demo_url' => 'http://phpfox3.demo.younetco.com/musicsharing',
    'image_url' => 'http://phpfox.younetco.com/files/2012/06/advanced_music.jpg',
    'purchase' => 'http://phpfox.younetco.com/music-sharing-v3.html',
    'download' => '',
    'price' => '60.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Music Sharing plug-in creates a place for users to share their favorite songs and artists with phpFox communities. Users can upload songs and create their theme albums/playlists. Also, songs are available for downloading and for sharing via other social networks such as Facebook, Twitter.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'gettingstarted{3}' => 
  array (
    'key' => 'gettingstarted',
    'name' => 'Getting Started',
    'current_v' => '3.02p5',
    'latest_v' => '3.02p5',
    'demo_url' => 'http://phpfox3demo.modules2buy.com/gettingstarted/',
    'image_url' => 'http://phpfox.younetco.com/files/2011/10/gettingstarted.jpg',
    'purchase' => 'http://phpfox.younetco.com/getting-started-v3.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Getting Started allows you to give your users all helpful guides to use your website, include:

+ To-do List: allow admin to design recommended steps to help members get familiar with the website.
+ Knowledge Base: admin can highlights information about features, modules on website to address users’ needs quickly and efficiently.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'AdSeo{3}' => 
  array (
    'key' => 'AdSeo',
    'name' => 'SEO/Sitemap',
    'current_v' => '3.01p5',
    'latest_v' => '3.01p5',
    'demo_url' => 'http://phpfox3demo.modules2buy.com',
    'image_url' => 'http://phpfox.younetco.com/files/2011/05/sitemap.jpg',
    'purchase' => 'http://phpfox.younetco.com/seo-v3.html',
    'download' => '',
    'price' => '40.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'SEO / Sitemap optimizes phpFox social networks for SEO (Search Engine Optimization). SEO module allows site admins to customize titles, Meta keywords, Meta descriptions for most page contents in their social networks, this makes these contents be more SEO-friendly. In addition, this module also supports sitemap generation for all network contents which boosts site visibility in search engines.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'contactimporter{3}' => 
  array (
    'key' => 'contactimporter',
    'name' => 'Contact Importer',
    'current_v' => '3.05p1',
    'latest_v' => '3.05p1',
    'demo_url' => 'http://phpfox3.demo.younetco.com/contactimporter/',
    'image_url' => 'http://phpfox.younetco.com/files/2012/06/contactimporter.png',
    'purchase' => 'http://phpfox.younetco.com/contact-importer-v3.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Contact Importer plugin is a great tool for users to expand their friend networks by inviting people from all social networks (Facebook, LinkedIn, Twitter, Hotmail, etc.). In addition, this plugin also empowers users to connect to all contacts from all major Email Providers.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'younet_document{3}' => 
  array (
    'key' => 'younet_document',
    'name' => 'User Document / Scribd iPaper',
    'current_v' => '3.02p3',
    'latest_v' => '3.02p3',
    'demo_url' => 'http://phpfox3.demo.younetco.com/document',
    'image_url' => 'http://phpfox.younetco.com/files/2011/08/scribd_docs.png',
    'purchase' => 'http://phpfox.younetco.com/document-v3.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Document plugin leverages Scribd’s features (www.scribd.com). Document plugin includes many features that help users manage their documents easily. Most document types (.pdf, .docx, .pptx, .xls, etc…) can be uploaded and shared among network members. In addition, published documents can be viewed directly online without using any reading plugin / software. On-page action feature allows site admin to edit / delete / set feature to members’ documents in just a click. Also, statistic block helps promote site by highlighting total views, total likes, and total documents.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'YouNetFeedBack{3}' => 
  array (
    'key' => 'YouNetFeedBack',
    'name' => 'Feedback/User Voice',
    'current_v' => '3.01p12',
    'latest_v' => '3.01p12',
    'demo_url' => 'http://phpfox3.demo.younetco.com/feedback',
    'image_url' => 'http://phpfox.younetco.com/files/2011/09/feedback.png',
    'purchase' => 'http://phpfox.younetco.com/feed-back-v3.html',
    'download' => '',
    'price' => '35.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Feedback plugin is a great tool to increase the interaction between users and your site. This plugin empowers users to voice out their opinions to help site admin to improve site content magnificently. Also, easy-to-use feedback features allow users to effectively manage their feedbacks and other members’ feedbacks.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
  'EmailSystem{3}' => 
  array (
    'key' => 'EmailSystem',
    'name' => 'Email System',
    'current_v' => '3.02',
    'latest_v' => '3.02',
    'demo_url' => 'http://phpfox3demo.modules2buy.com',
    'image_url' => 'http://phpfox.younetco.com/files/2011/05/email.jpg',
    'purchase' => 'http://phpfox.younetco.com/email-system-v3.html',
    'download' => '',
    'price' => '50.00',
    'currency' => 'USD',
    'is_active' => '1',
    'sort_description' => 'Email System/Newsletter plugin is developed to meet auto sending emails needs on phpFox sites. Admin can set up email system, compose unique email content, and configure email sending schedules. Using Email System, users will be easily reminded of upcoming events by receiving auto sending emails.',
    'platform' => 'phpfox',
    'mode' => 'product',
    'platform_version' => '3',
  ),
); ?>